import json
import os
import logging
from subprocess import call
import traceback

import boto3.session
import botocore.exceptions

# TODO: need to check folder

# user specified environment variable
UPLOADBUCKET = os.getenv('output_s3_name')
QUEUEURL = os.getenv('sqs')
REGION = os.getenv('AWS_DEFAULT_REGION')
NAME = os.getenv('NAME', default='%(name)s')

# user define if want to zip the result file
NEED_ZIP = os.getenv('ZIP', default='True')

# get input/output file location
INPUT_PATH = '%(input)s'
OUTPUT_PATH = '%(output)s'


logger = logging.getLogger()
log_lvl = os.getenv('LOG_LVL', default='WARNING')

if log_lvl == 'ERROR':
    logger.setLevel(logging.ERROR)
elif log_lvl == 'INFO':
    logger.setLevel(logging.INFO)
elif log_lvl == 'DEBUG':
    logger.setLevel(logging.DEBUG)
else:
    logger.setLevel(logging.WARNING)


def pull_files(message_URL):
    '''
    pull message form message_URL
    '''
    session = boto3.session.Session(region_name=REGION)
    s3 = session.client('s3')
    sqs = session.client('sqs')
    msgs = {}
    while 'Messages' not in msgs:
        logger.debug('pull message from SQS: {}'.format(message_URL))
        try:
            msgs = sqs.receive_message(QueueUrl=message_URL)
        except botocore.exceptions.ClientError as err:
            logger.debug(traceback.format_exc())
            logger.warn(err.response)
            continue
        except Exception as err:
            logger.debug(traceback.format_exc())
            logger.error('Unexpected error occures at pull_files()!!')
            logger.error(err)
            continue

        if '\"Records\"' not in msgs['Messages'][0]['Body']:
            # delete such message
            try:
                sqs.delete_message(QueueUrl=message_URL,
                                   ReceiptHandle=msgs['Messages'][0]['ReceiptHandle'])
            except botocore.exceptions.ClientError as err:
                logger.debug(traceback.format_exc())
                logger.warn(err.response)
            except Exception as err:
                logger.debug(traceback.format_exc())
                logger.error('Unexpected error occures when delete message!!')
                logger.error(err)
            logger.info('delete one message from file queue')
            msgs = {}

    logger.info('receive file info from SQS')
    for msg in msgs['Messages']:
        record = json.loads(msg['Body'])['Records'][0]
        bucket = record['s3']['bucket']['name']
        file = record['s3']['object']['key']

        # delete message
        try:
            sqs.delete_message(QueueUrl=message_URL,
                               ReceiptHandle=msg['ReceiptHandle'])
        except botocore.exceptions.ClientError as err:
            logger.debug(traceback.format_exc())
            logger.warn(err.response)
        except Exception as err:
            logger.debug(traceback.format_exc())
            logger.error('Unexpected error occures when delete message!!')
            logger.error(err)
        logger.info('delete one message from file queue')

        # download file from input S3 bucket
        input_file = download_file(bucket, file, msg)
        if input_file == '':
            continue

        # run program
        result = run_program(input_file)

        # upload file
        upload_file(result)


def download_file(bucket, file, msg):
    file_name = file.split('/')[-1]
    try:
        s3.download_file(bucket, file, INPUT_PATH + file_name)
        return INPUT_PATH + file_name
    except Exception as err:
        # This part has problem. formate is wrong
        # put the failed file info back to sqs
        logger.warn(err)
        logger.debug(traceback.format_exc())
        logger.debug('message content: {}'.format(json.dumps(msg)))
        logger.info('put message back to SQS for later try')
        try:
            sqs.send_message(QueueUrl=message_URL,
                             MessageBody=json.dumps(msg))
        except Exception as err:
            logger.warn(err)
            logger.debug(traceback.format_exc())
            return ''
        return ''


def run_program(input_file):
    command = '%(command)s'
    run_command = command.split()
    for i in range(len(run_command)):
        if run_command[i] == '$input':
            run_command[i] = input_file
    call(run_command)

    file_name = input_file.split('/')[-1]

    #check if need to zip
    if NEED_ZIP == 'True':
        file_name = 'Result-' + NAME + '-' + file_name.split('.')[0] + '.zip'
        call(['zip', '-rv9', file_name, OUTPUT_PATH])
    else:
        call(['cp', OUTPUT_PATH, file_name])
    return file_name


def upload_file(file):
    try:
        s3.upload_file(file, UPLOADBUCKET, file)
    except botocore.exceptions.ClientError as err:
        logger.warn(err)
    except Exception as err:
        logger.debug(traceback.format_exc())
        logger.error('Unexpected error happend will upload file')
        logger.err(err)


if __name__ == '__main__':
    pull_files(QUEUEURL)
